apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb
  namespace: default  # Make sure this matches your ServiceAccount's namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-role
subjects:
- kind: ServiceAccount
  name: build-sa
  namespace: default
  apiGroup: ""  # This must be empty for ServiceAccount
