apiVersion: v1
kind: Pod
metadata:
  name: load-generator
spec:
  containers:
  - name: load-generator
    image: busybox:1.28
    command: ["/bin/sh", "-c"]
    args: ["while sleep 0.01; do wget -q -O- http://php-apache; done"]
    resources:
      limits:
        cpu: "500m"
        memory: "128Mi"
      requests:
        cpu: "250m"
        memory: "64Mi"
  restartPolicy: Never


# # This YAML file defines a Pod named "load-generator" that runs a busybox container.
# # The container runs a command that continuously sends HTTP requests to the "php-apache" service.