apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2025-04-09T07:03:16Z"
  labels:
    run: nginx
  name: nginx
  namespace: default
  resourceVersion: "9272"
  uid: e715533b-3222-4d10-8497-dfaff8dede26
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
  nodeName: desktop-worker