# This YAML defines a Kubernetes Service that exposes Nginx pods to external traffic

# API version and resource type
apiVersion: v1    # Core Kubernetes API version
kind: Service     # Defines this as a Service resource

# Service metadata
metadata:
  name: nginx-service  # Unique name for the Service

# Service specification
spec:
  type: NodePort      # Service type that exposes pods on a static port on each node
  selector:           # Pod selector - service will route traffic to pods with these labels
    app: nginx        # Matches pods with label app=nginx
  ports:             # Port configuration
    - port: 80         # Port exposed internally in the cluster
      targetPort: 80   # Port on the pod that receives traffic
      nodePort: 30007  # External port opened on each node (must be between 30000-32767)