apiVersion: v1
kind: Pod
metadata:
  labels:
    run: redis
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  tolerations:
  - key: "gpu"
    operator: "Equal"
    value: "true"
    effect: "NoSchedule"
# first we taint the node with the key gpu and value true
# kubectl taint nodes desktop-worker gpu=true:NoSchedule
# then we can schedule the pod on the node with the same key and value
# kubectl apply -f affinity.yaml
# kubectl get pods -o wide
# kubectl describe pod redis
# the pod will be scheduled on the node with the same key and value